version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: prontu_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  seed:
    build: .
    container_name: prontu_seed
    command: python seed.py
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017/
    restart: "no"

  app:
    build: .
    container_name: prontu_app
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
    environment:
      MONGO_URI: mongodb://mongo:27017/
    volumes:
      - ./static/uploads:/app/static/uploads

volumes:
  mongo_data:
